swiftmailer:
    transport:        gmail
    username:         truckeetrout@gmail.com
    password:         X3^lc7Q3
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }
    sender_address: 'admin@bogus.info'