imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        secured_area:
            http_basic:

liip_functional_test: ~
#    cache_sqlite_db: true
        
doctrine:
    dbal:
        default_connection: test
        connections:
            test:
#        default_connection:   default
                driver:   pdo_mysql
                host:     localhost
                port:     3306
                dbname:   projectmana_test
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types: 
                    enum:       string 
