imports:
    - { resource: parameters.yml }
    - { resource: easyAdmin.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum:       string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
          default:
            auto_mapping: true
            dql:
                numeric_functions:
                    fy: Truckee\ProjectmanaBundle\DQL\FiscalYearFunction
                    age: Truckee\ProjectmanaBundle\DQL\AgeFunction

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

braincrafted_bootstrap:
     css_preprocessor: lessphp

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: 'Truckee\ProjectmanaBundle\Entity\User'
    from_email:
        address:        Projectmana.app@gmail.com
        sender_name:    Application Support
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: email/password_resetting.email.twig

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        lessphp:
             file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
             apply_to: '\.less$'
        cssrewrite: ~

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: BraincraftedBootstrapBundle:Menu:bootstrap.html.twig
