mana_project:
    resource: "@TruckeeProjectmanaBundle/Controller/"
    type:     annotation

logout:
    path:   /logout

home:
    path: /
    defaults:  { _controller: TruckeeProjectmanaBundle:Default:index }

easy_admin_bundle:
    resource: "@TruckeeProjectmanaBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /optionsAdmin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
