mana_household:
    resource: "@ManaClientBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path:   /login_check

login_path:
  path: /login

logout:
    path:   /logout

root:
    path: /
    defaults:  { _controller: ManaClientBundle:Default:index }
       
home:
    path: /home
    defaults:  { _controller: ManaClientBundle:Default:index }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /optionsAdmin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
