mana_household:
    resource: "@ManaClientBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern:   /login_check

login_path:
  pattern: /login

logout:
    pattern:   /logout

root:
    pattern: /
    defaults:  { _controller: ManaClientBundle:Default:index }
       
home:
    pattern: /home
    defaults:  { _controller: ManaClientBundle:Default:index }
