mana_project:
    resource: "@ManaClientBundle/Controller/"
    type:     annotation

logout:
    path:   /logout

root:
    path: /
    defaults:  { _controller: ManaClientBundle:Default:index }

easy_admin_bundle:
    resource: "@ManaClientBundle/Controller/ManaUserController.php"
    type:     annotation
    prefix:   /optionsAdmin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
