security:
    encoders:
      FOS\UserBundle\Model\UserInterface:
        algorithm: md5
        ignore_case: true
        encode_as_base64: false
        iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        foodbank:
          pattern: ^/reports/foodbank/*
          anonymous: ~

        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
#
        reset_firewall:
            pattern:    ^/resetting
            anonymous:  ~

        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /home
                use_referer: true

            logout:
              target: /login

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reports/foodbank/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }