security:
    encoders:
      old:
#      FOS\UserBundle\Model\UserInterface:
            algorithm: md5
            ignore_case: true
            encode_as_base64: false
            iterations: 1
      new:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        foodbank:
          pattern: ^/reports/foodbank/*
          anonymous: ~
          logout_on_user_change: true

        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
            logout_on_user_change: true
#
        reset_firewall:
            pattern:    ^/resetting
            anonymous:  ~
            logout_on_user_change: true

        main:
            pattern:    ^/
            logout_on_user_change: true
            form_login:
                provider: fos_userbundle
                default_target_path: /
                use_referer: true

            logout:
              target: /login

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reports/foodbank/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }