services:
    form.type.dob_age:
      class: Truckee\ProjectmanaBundle\Form\Field\DobAgeType
      tags:
        - {name:form.type}

    searches:
      class: Truckee\ProjectmanaBundle\Utilities\Searches
      arguments:
        em: '@doctrine.orm.entity_manager'

    reports:
      class: Truckee\ProjectmanaBundle\Utilities\Reports
      arguments:
        em: '@doctrine.orm.entity_manager'

    status:
      class: Truckee\ProjectmanaBundle\Utilities\Status
      arguments:
        conn: '@doctrine.dbal.default_connection'

    mana.crosstab:
      class: Truckee\ProjectmanaBundle\Utilities\Crosstab

    mana.user_manipulator:
        class:      Truckee\ProjectmanaBundle\Utilities\UserManipulator
        arguments:  ['@fos_user.user_manager']

    app.menu_builder:
        class: Truckee\ProjectmanaBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@security.authorization_checker', '@request_stack']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: logoutMenu, alias: logout }
            - { name: knp_menu.menu_builder, method: reportsMenu, alias: reportsMenu }
            - { name: knp_menu.menu_builder, method: profileMenu, alias: profileMenu }
            - { name: knp_menu.menu_builder, method: householdMenu, alias: household }
            - { name: knp_menu.menu_builder, method: returnFromContacts, alias: return }
