services:
    mana.dob_age:
      class: Truckee\ProjectmanaBundle\Form\Field\DobAgeType
      tags:
        - {name: form.type}

    mana.searches:
      class: Truckee\ProjectmanaBundle\Utilities\Searches
      arguments: ['@doctrine.orm.entity_manager']

    mana.reports:
      class: Truckee\ProjectmanaBundle\Utilities\Reports
      arguments: ['@doctrine.orm.entity_manager']

    mana.status:
      class: Truckee\ProjectmanaBundle\Utilities\Status
      arguments: ['@doctrine.dbal.default_connection']

    mana.crosstab:
      class: Truckee\ProjectmanaBundle\Utilities\Crosstab

    mana.user_manipulator:
        class:      Truckee\ProjectmanaBundle\Utilities\UserManipulator
        arguments:  ['@fos_user.user_manager']

    mana.menu_builder:
        class: Truckee\ProjectmanaBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@security.authorization_checker', '@request_stack']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: logoutMenu, alias: logout }
            - { name: knp_menu.menu_builder, method: reportsMenu, alias: reportsMenu }
            - { name: knp_menu.menu_builder, method: profileMenu, alias: profileMenu }
            - { name: knp_menu.menu_builder, method: householdMenu, alias: household }
            - { name: knp_menu.menu_builder, method: returnFromContacts, alias: return }
            - { name: knp_menu.menu_builder, method: databaseMenu, alias: databaseMenu }

    mana.addresses:
        class: Truckee\ProjectmanaBundle\Utilities\Addresses
        arguments: ['@doctrine.orm.entity_manager']
