services:
    mana_exception_listener:
        class: Mana\ClientBundle\Listeners\CustomExceptionListener
        arguments: ['@twig', '%mailer_user%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
