services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Truckee\ProjectmanaBundle\:
        resource: '../../src/Truckee/ProjectmanaBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/Truckee/ProjectmanaBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Truckee\ProjectmanaBundle\Controller\:
        resource: '../../src/Truckee/ProjectmanaBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    mana.dob_age:
      class: Truckee\ProjectmanaBundle\Form\Field\DobAgeType
      tags:
        - {name: form.type}

    mana.searches:
      class: Truckee\ProjectmanaBundle\Utilities\Searches
      arguments: ['@doctrine.orm.entity_manager']
      public: true

    mana.status:
      class: Truckee\ProjectmanaBundle\Utilities\Status
      arguments: ['@doctrine.dbal.default_connection']
      public: true

    mana.menu_builder:
        class: Truckee\ProjectmanaBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@security.authorization_checker', '@request_stack']
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: logoutMenu, alias: logout }
            - { name: knp_menu.menu_builder, method: reportsMenu, alias: reportsMenu }
            - { name: knp_menu.menu_builder, method: profileMenu, alias: profileMenu }
            - { name: knp_menu.menu_builder, method: householdMenu, alias: household }
            - { name: knp_menu.menu_builder, method: returnFromContacts, alias: return }
            - { name: knp_menu.menu_builder, method: databaseMenu, alias: databaseMenu }

    mana.addresses:
        class: Truckee\ProjectmanaBundle\Utilities\Addresses
        arguments: ['@doctrine.orm.entity_manager']
        public: true

    Truckee\ProjectmanaBundle\Utilities\PdfService:
        arguments:
            $os: '%os%'

    Braincrafted\Bundle\BootstrapBundle\Session\FlashMessage:
        public: false

    braincrafted_bootstrap.flash:
        alias: Braincrafted\Bundle\BootstrapBundle\Session\FlashMessage
        public: true

    mana.userListener:
        class: Truckee\ProjectmanaBundle\EventListener\UserListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@security.password_encoder'
        tags:
            - name: kernel.event_listener
              event: security.interactive_login
              
    Truckee\ProjectmanaBundle\Utilities\GeneralStatisticsReport:
        arguments: ['@doctrine.orm.entity_manager']
