# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
#    transport:        smtp
#    username:         admin@bogus.info
#    password:         123Abcd
#    host:             localhost
    delivery_addresses: ['admin@bogus.info']
    disable_delivery: false
