security:
    encoders:
      Mana\ClientBundle\Entity\User: 
        algorithm: md5
        ignore_case: true
        encode_as_base64: false
        iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity:
          entity:
            class: Mana\ClientBundle\Entity\User
            property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        foodbank:
          pattern: ^/reports/foodbank/*
          anonymous: ~

        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        
        secured_area:
            pattern:    ^/
            form_login:
              default_target_path: /home
              use_referer: true

            logout:
              target: /login

    access_control:
        - { path: ^/reports/foodbank/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }