services:
    form.type.dob_age:
      class: Mana\ClientBundle\Form\Field\DobAgeType
      tags:
        - {name:form.type, alias:dob_age}
    searches:
      class: Mana\ClientBundle\Utilities\Searches
      arguments: 
        em: @doctrine.orm.entity_manager
    reports:
      class: Mana\ClientBundle\Utilities\Reports
      arguments:
        conn: @doctrine.dbal.default_connection
    status:
      class: Mana\ClientBundle\Utilities\Status
      arguments:
        conn: @doctrine.dbal.default_connection

    mana.head.replacement:
      class: Mana\ClientBundle\Utilities\HouseholdHeadReplacement
    mana.crosstab:
      class: Mana\ClientBundle\Utilities\Crosstab
      arguments: 
        em: @doctrine.orm.entity_manager

    mana_exception_listener:
        class: Mana\ClientBundle\Listeners\CustomExceptionListener
        arguments: ['@twig', '%mailer_user%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
