monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    'group'
            members: [streamed, deduplicated]
        streamed:
            type:  'stream'
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: 'debug'
        deduplicated:
            type:    'deduplication'
            handler: 'swift'
        swift:
            type:       'swift_mailer'
            from_email: 'admin@projectmana.org'
            to_email:   'support@projectmana.org'
            subject:    'Project MANA Error Alert!'
            level:      'debug'
            formatter:  'monolog.formatter.html'
            content_type: 'text/html'
## yaml as delivered:
#    handlers:
#        main:
#            type: fingers_crossed
#            action_level: error
#            handler: nested
#            excluded_404s:
#                # regex: exclude all 404 errors from the logs
#                - ^/
#        nested:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine"]
#        deprecation:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
#        deprecation_filter:
#            type: filter
#            handler: deprecation
#            max_level: info
#            channels: ["php"]
